### ISSUE TITLE
Show the preset configuration options at the landscape screen

### ISSUE THREAD

**Issue by renanfranca** [jhipster/jhipster-lite#10379]
Add a select box to the landscape screen with the preset configurations. The modules should be automatically selected after choosing one of the preset configurations.

See https://github.com/jhipster/jhipster-lite/issues/9491 description for the complete roadmap.

### To-Do
- [x] Render `LandscapePresetConfigurationVue` component
- [x] Select modules from selected preset
- [x] Retain module selection state when preset option is deselected
- [x] Deselect preset option when a new module is selected
- [x] Retain preset option when trying to select a new non-selectable module
- [x] Deselect preset option when a selected module is deselected

**Comment by renanfranca** [comment]
FYI: I am currently facing a learning curve with the Tikui framework to add style to the component. I've already implemented the preset configuration behavior.

**Comment by renanfranca** [comment]
Here is a demo of using the preset configurations 😃💙:


https://github.com/user-attachments/assets/8ef6389f-a363-42a4-b78d-88e9bf0f5389

**Comment by renanfranca** [comment]
@pascalgrimaud: Bounty Claimed https://opencollective.com/generator-jhipster/expenses/215555. Thanks 😀✌
