### ISSUE TITLE
Add a search module bar to the landscape screen

### ISSUE THREAD

**Issue by renanfranca** [jhipster/jhipster-lite#11102]
~~### Prerequisite~~

~~- [ ] Add a button to hide the properties form component (needed on small device screens)~~
~~- [ ] Memorize in local storage the hide/show preference options selected by the user from the minimap/presetConfiguration/propertiesForm components. This will avoid the annoying situation of having to hide or show components every time they press F5 or access JHipster Lite. `ComponentsVisibilityRepository`-> `LocalStorageComponentsVisibilityRepository`~~
~~- [ ] Use an icon on the minimap instead of the large `OPEN MINIMAP` button to optimize screen space~~

### TODO (edited: 20241012)

- [x] Implement a search functionality in the modules bar that identifies the module/feature by name as each letter is typed
- [x] Highlight the first module/feature that matches the typed letters in the search modules bar
- [x] Scroll the screen to the highlighted module if it is not visible within the current viewport
- [x] Reset the screen position to the initial landscape layout when the search bar is cleared
- [x] Remove the hilight when the search bar is cleared.
- [x] Hide the search modules bar on devices with screens smaller than or equal to 800px, as it becomes impractical to use without the option to hide other components

### Demo of the prototype to show the viability of this feature

The recorded video missed some frames and is lagging, but it's super smooth to use. Please ignore the search button, as it wasn't needed.

https://github.com/user-attachments/assets/d3ab75c1-0138-4628-a67e-d769ba6be938

**Comment by pascalgrimaud** [comment]
Thanks @renanfranca  but for the 1st version, keep it simple plz:
- search module bar
- highlight the modules related to the input text
- it should be closed to your video

No need local storage, no need minimap, no need to hide properties, etc...
At least for a 1st version. The other points can be discussed further, after some 1st feedbacks

**Comment by renanfranca** [comment]
I updated the TODO in the description to focus on small steps and quick delivery. I removed the Prerequisites. 

> TODO (edited: 20241012)
 [ ] Implement a search functionality in the modules bar that identifies the module/feature by name as each letter is typed.
 [ ] Highlight the first module/feature that matches the typed letters in the search bar.
 [ ] Scroll the screen to the highlighted module if it is not visible in the current viewport.
 [ ] Reset the screen position to the initial landscape layout when the search bar is cleared.
 [ ] Remove the hilight when the search bar is cleared.
 [ ] Hide the search bar on devices with screens smaller than or equal to 1024px, as it becomes impractical to use without the option to hide other components.

Thanks for the feedback, @pascalgrimaud, and for bringing me back down to earth, haha. I was so confident that it was a killer feature that I was trying to make the most of it. But it's better to collect other opinions.

**Comment by pascalgrimaud** [comment]
Adding a bounty for the amount of work and this really nice feature.
Thanks for your hard work @renanfranca

**Comment by renanfranca** [comment]
Thank you very much @pascalgrimaud! I am looking forward to the feedback from everyone who can try it; I am all ears ;)

I am going to share the demonstration video here too:

https://github.com/user-attachments/assets/b09eede8-6a7e-4f8d-bf18-4523f123915a

**Comment by renanfranca** [comment]
@pascalgrimaud: Bounty Claimed  https://opencollective.com/generator-jhipster/expenses/226386. Thanks 💙😄

**Comment by pascalgrimaud** [comment]
@renanfranca : approved
