### ISSUE TITLE
Vue: add OAuth2 keycloak authentication

### ISSUE THREAD

**Issue by Franceq34** [jhipster/jhipster-lite#1133]
**Prerequisites**
- [x] https://github.com/jhipster/jhipster-lite/pull/10712
- [x] https://github.com/jhipster/jhipster-lite/issues/10876

**TO-DO**
- [x] Create a sample project that adds the OAuth2 Keycloak module to the Vue frontend client and shows it working with login and logout
- [x] Create the `vue-oauth2-keycloak` module in the JHLite project which depends on `vue-core` module
  - [x] Use `keycloak-js` dependency from COMMON package at `AngularOAuth2ModulesFactory` and remove it from ANGULAR package

**Comment by pascalgrimaud** [comment]
@Franceq34 : as you didn't start it yet, maybe @Bolo89 can take this ?

**Comment by pascalgrimaud** [comment]
Adding a bounty to motivate someone
Did you start this one @Bolo89 ?

**Comment by Bolo89** [comment]
@pascalgrimaud the ticket is not started so someone else can take it

**Comment by pascalgrimaud** [comment]
Increasing the bounty to motivate people as it's a good feature to have

**Comment by DamnClin** [comment]
Warning : the goal is to build something modular and not doing lots of replacement to have something we can trust in time

**Comment by pascalgrimaud** [comment]
Totally agree, and maybe we should not do the same code than in generator-jhipster and produce a dedicated for jhlite

**Comment by DamnClin** [comment]
Totally. I think I have working integration but I need to think of a modular mechanism AND this is far from being my personal priority for JHLite :⁠-⁠). Cc @Gnuk

**Comment by renanfranca** [comment]
@pascalgrimaud: Bounty Claimed https://opencollective.com/generator-jhipster/expenses/221556. Thanks 😄👍
